name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".github/**"
    tags: ["*"]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v3

    -
      name: Log in to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    -
      name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest --target production

    -
      name: Push to Docker hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest



